### ISSUE TITLE
Errors on weekly menu for dining halls

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-sdk-python#22]
Almost certainly has to do with #21. Tagging @sachabest because it's crashing the iOS app, this bug needs to be squashed ASAP for iOS dining to function.

Demo:
```
>>> import os
>>> from penn import dining
>>> din = dining.Dining(os.getenv("DIN_USERNAME"), os.getenv("DIN_PASSWORD"))
>>> din.menu_weekly("638")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "penn/dining.py", line 83, in menu_weekly
    return normalize_weekly(response)
  File "penn/dining.py", line 17, in normalize_weekly
    if isinstance(meal["tblStation"], dict):
TypeError: string indices must be integers
```

**Comment by awiss** [comment]
Fixed in https://github.com/pennlabs/penn-sdk-python/pull/23
